### ISSUE TITLE
What mirror exists for Community Python? (repo is offline)

### ISSUE THREAD

**Issue by intel352** [hadim/QCouchPotato#4]
The community repo site is offline/down, is there another repo host that has the proper version of python?

**Comment by intel352** [comment]
@hadim ping

**Comment by hadim** [comment]
No idea. I don't use this repo anymore. I have switched to docker images.

**Comment by intel352** [comment]
Might be a good idea to update the readme then, since it's obsolete. Thanks anyhow, I'll check out Radarr.
